baseurl = "https://paulbutler.org/"
languageCode = "en-us"
title = ""

[blackfriday]
  extension = ["footnotes"]

[permalinks]
  posts = "/:year/:slug/"

[context.production.environment]
HUGO_VERSION = "0.67.1"
HUGO_ENV = "production"